apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: printed-possum-python 
  janus-idp.io/tekton: printed-possum-python
  backstage.io/kubernetes-id: printed-possum-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: printed-possum-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  