apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: printed-possum-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: printed-possum-python 
  name: printed-possum-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: printed-possum-python 
